server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccinationCenter
    username: root
    password: Sinha@12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: VACCINATION-CENTRE-SERVICE